// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhojixpvwjgwuijuityq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFob2ppeHB2d2pnd3VpanVpdHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODM1NzgsImV4cCI6MjA1NjE1OTU3OH0.I0TXlSDFFkBVHAlut9lihvD1TrYOzaypzrMZmo6GZyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);